a= list(map(int,input().split(' '))
k = int(input())
a.sort()
print(a[:k])
a= list(map(int,input().split(' '))
k = int(input())
a.sort()
print(a[:k])
<<<<<<< Updated upstream
        hey
=======
a= list(map(int,input().split(' '))
k = int(input())
a.sort()
print(a[:k])
a= list(map(int,input().split(' '))
k = int(input())
a.sort()
print(a[:k])
a= list(map(int,input().split(' '))
k = int(input())
a.sort()
print(a[:k])
a= list(map(int,input().split(' '))
k = int(input())
a.sort()
print(a[:k])
a= list(map(int,input().split(' '))
k = int(input())
a.sort()
print(a[:k])
a= list(map(int,input().split(' '))
k = int(input())
a.sort()
print(a[:k])
a= list(map(int,input().split(' '))
k = int(input())
a.sort()
print(a[:k])
a= list(map(int,input().split(' '))
k = int(input())
a.sort()
print(a[:k])
>>>>>>> Stashed changes
